name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ID_TOKEN: ${{ secrets.ID_TOKEN }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      SCRIPT_ID: ${{ secrets.SCRIPT_ID }}
      DEPLOYMENT_ID: ${{ secrets.DEPLOYMENT_ID }}

    steps:
      - name: Setup repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install clasp
        run: npm install -g @google/clasp@latest

      - name: Generate ~/.clasprc.json
        run: |
          bash deployment/setup.sh
      - name: Generate ~/.clasp.json
        run: |
          bash deployment/setup_claspjson.sh
      - name: Push
        run: |
          cd src
          clasp push --force
      - name: DEPLOY
        run: |
          cd src
          clasp deploy --deploymentId $DEPLOYMENT_ID
