name: Deploy to GAS

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Deploy via clasp
        run: npx clasp push
        env:
          CLASPRC_JSON: ${{ secrets.CLASPRC_JSON }}
