name: Deploy GAS
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via Google Apps Script Action
        uses: Mayu-mic/google-apps-script-action@v2
        with:
          clasprc: ${{ secrets.CLASPRC_JSON }}
          scriptId: ${{ secrets.SCRIPT_ID }}
          command: 'deploy'
          deploymentId: ${{ secrets.DEPLOYMENT_ID }}
          description: 'Auto-deploy via GitHub Actions'
          sourceRootDir: 'src'
          claspOptions: '--type webapp --deploymentId ${{ secrets.DEPLOYMENT_ID }}'