name: Deploy GAS
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install clasp
        run: npm install -g @google/clasp@latest

      - name: Configure clasp
        env:
          CLASPRC_JSON: ${{ secrets.CLASPRC_JSON }}
          SCRIPT_ID: ${{ secrets.SCRIPT_ID }}
        run: |
          echo "$CLASPRC_JSON" > ~/.clasprc.json
          echo '{"scriptId":"'"$SCRIPT_ID"'"}' > .clasp.json

      - name: Push
        run: clasp push --force

      - name: Deploy
        env:
          DEPLOYMENT_ID: ${{ secrets.DEPLOYMENT_ID }}
        run: |
          clasp deploy \
            --deploymentId "$DEPLOYMENT_ID" \
            --description "Auto-deploy via GitHub Actions ($(date +'%Y-%m-%d %H:%M'))"